#!perl

# DATE
# VERSION

use strict;
use warnings;

if (@ARGV == 0) {
    die "Usage: $0 <string> ...\n";
}

require App::wordlist;
my $res = App::wordlist::wordlist(
    arg => \@ARGV,
    wordlists => ['CryptoCurrency::Catalog::NameSymbol'],
);

require Perinci::Result::Format::Lite;
print Perinci::Result::Format::Lite::format($res, 'text');

# ABSTRACT: Grep cryptocurrencies
# PODNAME:

=head1 SYNOPSIS

 % grepcrypto <symbol-or-name>


=head1 DESCRIPTION

This utility greps cryptocurrencies from
L<WordList::CryptoCurrency::Catalog::NameSymbol>, which in turn gets its list
from L<CryptoCurrency::Catalog>, which in turn gets its list from
L<https://coinmarketcap.com> with some modification.


=head1 SEE ALSO
